### ISSUE TITLE
Planning for PBL

### ISSUE THREAD

**Issue by Saaras859** [Saaras859/Saaras_2025#12]
# Tasks

- [ ] login page with Javascript
- [ ] kahoot quiz backend for teacher input
- [ ] leaderboard
- [ ] homepage of games to choose from
- [ ] Blackjack Game
- [ ] Dice Game
- [ ] Score Analysis
- [ ] Plinko Balls

**Comment by Saaras859** [comment]
## Arthur : Scrum Master
- [ ]  
## Hanlun : 
- [ ]  
## Saraas : 
- [ ] 
## Alisha : 
- [ ]
