### ISSUE TITLE
What I need to get done

### ISSUE THREAD

**Issue by Saaras859** [Saaras859/Saaras_2025#15]
### Task: FRQ Collaboration and Integration Assistance

**To-Do List**

- [x] Collaborate with Eric to track and document what the entire class is working on regarding FRQs.
- [x] Select an FRQ for the class to focus on and ensure everyone adheres to that selection.
- [x] Assist with any issues related to integration for the product teams (User to Person).
- [x] Lead the class in working through the FRQ and resolve any questions or issues that arise.
